controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

delete_inactive_questions:
    path: '/delete-inactive-questions'
    controller: 'App\Controller\DeleteInactiveQuestionsController::deleteInactiveQuestions'

export_route:
    path: '/export'
    controller: 'App\Controller\StaticController::exportToPdf'